### ISSUE TITLE
OpenJDK 17 启动异常

### ISSUE THREAD

**Issue by cx1293872055** [beansoftapp/visualgc_idea#2]
![image](https://user-images.githubusercontent.com/39186516/156131415-b19322df-aabf-457b-80d3-7a4474a6b2c1.png)

![image](https://user-images.githubusercontent.com/39186516/156131519-8e6f2a55-fe86-4f9c-93a5-6a17d3beab22.png)

java.lang.IllegalAccessError: class github.beansoftapp.visualgc.JpsHelper (in unnamed module @0x5c687e28) cannot access class sun.jvmstat.monitor.MonitorException (in module jdk.internal.jvmstat) because module jdk.internal.jvmstat does not export sun.jvmstat.monitor to unnamed module @0x5c687e28
	at github.beansoftapp.visualgc.JpsHelper.getJvmPSList(JpsHelper.java:126)
	at com.sun.jvmstat.tools.visualgc.VisualGCPane$PsListModel.actionPerformed(VisualGCPane.java:618)
	at java.desktop/javax.swing.Timer.fireActionPerformed(Timer.java:311)
	at java.desktop/javax.swing.Timer$DoPostEvent.run(Timer.java:243)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:777)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:728)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:747)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:891)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:760)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:447)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:818)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:446)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:498)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by beansoft** [comment]
这个和IDEA JDK的配置有关 试试
https://www.jianshu.com/p/d6cd7837831c


--add-exports=jdk.internal.jvmstat/sun.jvmstat.monitor=ALL-UNNAMED

**Comment by beansoft** [comment]
或者下载试用默认的 JBR 11 版本的 IDEA

**Comment by beansoft** [comment]
完整的配置列表:
--add-opens=java.desktop/java.awt.event=ALL-UNNAMED
--add-opens=java.desktop/sun.font=ALL-UNNAMED
--add-opens=java.desktop/java.awt=ALL-UNNAMED
--add-opens=java.desktop/sun.awt=ALL-UNNAMED
--add-opens=java.base/java.lang=ALL-UNNAMED
--add-opens=java.base/java.util=ALL-UNNAMED
--add-opens=java.desktop/javax.swing=ALL-UNNAMED
--add-opens=java.desktop/sun.swing=ALL-UNNAMED
--add-opens=java.desktop/javax.swing.plaf.basic=ALL-UNNAMED
--add-opens=java.desktop/java.awt.peer=ALL-UNNAMED
--add-opens=java.desktop/javax.swing.text.html=ALL-UNNAMED
--add-exports=java.desktop/sun.font=ALL-UNNAMED
--add-exports=java.desktop/sun.java2d=ALL-UNNAMED
--add-exports=java.desktop/sun.awt.windows=ALL-UNNAMED
--add-exports=java.desktop/sun.awt.image=ALL-UNNAMED
--add-opens=java.desktop/sun.awt.windows=ALL-UNNAMED
--add-exports=jdk.internal.jvmstat/sun.jvmstat.monitor=ALL-UNNAMED
--add-exports=jdk.internal.jvmstat/sun.jvmstat.monitor.event=ALL-UNNAMED

**Comment by cx1293872055** [comment]
这个异常倒是没了。

这个进程双击后没反应。
![image](https://user-images.githubusercontent.com/39186516/156285424-3ebe918c-f9af-4508-97f5-f6c5dc8e5099.png)

![image](https://user-images.githubusercontent.com/39186516/156285500-bb5137ef-b439-40f1-8169-dc24e9345b45.png)

**Comment by beansoft** [comment]
得加两行:

```
--add-exports=jdk.internal.jvmstat/sun.jvmstat.monitor=ALL-UNNAMED
--add-exports=jdk.internal.jvmstat/sun.jvmstat.monitor.event=ALL-UNNAMED
```

**Comment by cx1293872055** [comment]
你看第二张图，我加了的呀。

**Comment by beansoft** [comment]
我在Windows, Mac下都试了 没问题 双击速度要快一点才行 那个列表刷新的很快

**Comment by cx1293872055** [comment]
不是呀，老哥，只有IDEA 的这个进程没反应，其他的进程是正常的。

**Comment by cx1293872055** [comment]
换成G1GC 就好了，之前是ZGC
